### ISSUE TITLE
Issues with relative URL paths

### ISSUE THREAD

**Issue by anand-bhat** [qvl/httpsyet#8]
Installed version:

    >httpsyet.exe -version
    httpsyet 0.1.4 windows amd64

I'm seeing that in some cases, relative URL paths aren't being evaluated properly. For instance, on `https://designsystem.gov.au/get-started/`, the two links to install npm (`https://designsystem.gov.au/get-started/npm-install`) appear like this:
(1)
![image](https://user-images.githubusercontent.com/7332442/77080860-f09bf480-6a4d-11ea-9128-f9ad111e3279.png)

(2)
![image](https://user-images.githubusercontent.com/7332442/77081018-2214c000-6a4e-11ea-8cc3-10f67789e077.png)

However, httpsyet evaluates this to `https://designsystem.gov.au/npm-install` which is incorrect.

![image](https://user-images.githubusercontent.com/7332442/77081178-57b9a900-6a4e-11ea-81f2-a6a65dd66a4a.png)

**Comment by jorinvo** [comment]
Hey @anand-bhat, haven't touched this project in a while, but finally got around to build something to handle this case.

Hope it works as expected, in case you are still interested in giving it a try :)

There is a new release [v0.2.0](https://github.com/qvl/httpsyet/releases/tag/v0.2.0).

**Comment by anand-bhat** [comment]
Thanks! I'm continuing to see the same error with v0.2.0:

```
C:\Users\user\Downloads>httpsyet -version
httpsyet 0.2.0 windows amd64
```

```
C:\Users\user\Downloads>httpsyet https://designsystem.gov.au
404 https://designsystem.gov.au/home on page https://designsystem.gov.au/templates
404 https://designsystem.gov.au/core on page https://designsystem.gov.au/components
404 https://designsystem.gov.au/npm-install on page https://designsystem.gov.au/get-started
```
There is no link to `https://designsystem.gov.au/npm-install` from `https://designsystem.gov.au/get-started`. The URLs should resolve to `https://designsystem.gov.au/get-started/npm-install` as they do in the browser.

**Comment by jorinvo** [comment]
Thank you @anand-bhat for trying again. 

I gave it another spin. This time I not only tried to reproduce it via tests but also run the actual tool against the domain you provided.

The first fix I did was to support resolving relative links which do not start with with a prefix like `./`

Now I realized I also need to support resolving relative links relative to parent pages that do not end with a `/`

The example you provided showcases these two things nicely.

Now running [v0.2.1](https://github.com/qvl/httpsyet/releases/tag/v0.2.1) you should be able to see actual, interesting results for https://designsystem.gov.au :)

**Comment by anand-bhat** [comment]
Perfect @jorinvo! Thank you so much :) This now works well.
